irishcribs/django_messages/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from django_messages.views import *

app_name = 'django_messages'
urlpatterns = [
    url(r'^$', RedirectView.as_view(permanent=True, url='inbox/'), name='messages_redirect'),
    url(r'^inbox/$', inbox, name='messages_inbox'),
    url(r'^outbox/$', outbox, name='messages_outbox'),
    url(r'^compose/$', compose, name='messages_compose'),
    url(r'^compose/(?P<recipient>[\w.@+-]+)/$', compose, name='messages_compose_to'),
    url(r'^reply/(?P<message_id>[\d]+)/$', reply, name='messages_reply'),
    url(r'^view/(?P<message_id>[\d]+)/$', view, name='messages_detail'),
    url(r'^delete/(?P<message_id>[\d]+)/$', delete, name='messages_delete'),
    url(r'^undelete/(?P<message_id>[\d]+)/$', undelete, name='messages_undelete'),
    url(r'^trash/$', trash, name='messages_trash'),
]

irishcribs/irishcribs/urls.py
from django.contrib import admin
from django.urls import path, re_path, register_converter
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from . import converts

from home import views as home_view
from Users import views as user_views
from Listings import views as listing_views
from Listings.views import EditListingView, DeleteListingView

from Sublets import views as sublet_views
from Sublets.views import EditSubletView, DeleteSubletView

from MapQuery import views as map_views

register_converter(converts.FloatUrlParameterConverter, 'float')

urlpatterns = [
	path('accounts/', include('django.contrib.auth.urls')),
	path('accounts/signup/', user_views.signup, name='signup'),
    path('accounts/login/', user_views.login, name='login'),
    path('userAccount/', user_views.accountPage, name='user_account'),

	path('listings/', listing_views.view_listings, name='show_listing'),
    path('addlisting/', listing_views.add_listings, name='add_listing'),
    path('editlisting/<pk>/', EditListingView.as_view(), name='edit_listing'),
    path('deletelisting/<pk>/', DeleteListingView.as_view(), name='delete_listing'),
    #path('deleteListing/', listing_views.delete_listing, name='delete_listing'),
    path('filterListings/', listing_views.filter_listing_form, name='filter_listing_form'),
    #path('filteredListings/<float:bedrooms>/<float:bathrooms>/<float:rent>/<float:sqft>/<float:isApartment>/', listing_views.show_filtered_listings, name='filtered'),
    path('filteredListings/', listing_views.filtered_listings, name='filtered_listings'),
	path('messages/', include('django_messages.urls', namespace='django_messages')),
	path('sublets/', sublet_views.view_sublets, name='show_sublet'),
    path('addsublet/', sublet_views.add_sublets, name='add_sublet'),
    path('editsublet/<pk>/', EditSubletView.as_view(), name='edit_sublet'),
    path('deletesublet/<pk>/', DeleteSubletView.as_view(), name='delete_sublet'),
    path('filtersublets/', sublet_views.filter_sublet_form, name='filter_sublet_form'),
    path('filteredsublets/', sublet_views.filtered_sublets, name='filtered_sublets'),
    path('admin/', admin.site.urls),
    path('mapquery/', map_views.map_query, name='map_query'),
	path('area_listing/', map_views.area_listing, name='area_listing'),

	path('', home_view.home, name='home'),
	path('home/', home_view.home, name='home')
]

irishcribs/MapQuery/models.py
from django.db import models

# Create your models here.

irishcribs/MapQuery/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from Listings.models import Listing, listing_library
import googlemaps
import json
import datetime

gmaps = googlemaps.Client('AIzaSyBVYADTq8rJ8_7sl4QrOOB0Se_mnOCHDxg')
lib = listing_library()

# This is the function to actually display the filtered listings to the user
def map_query(request):

	#if request.is_ajax():
	listings = lib.get_all_listings()

	area_listings = []

	if request.is_ajax():
		n_bound = float(request.POST.get('north', 0))
		e_bound = float(request.POST.get('east', 0))
		s_bound = float(request.POST.get('south', 0))
		w_bound = float(request.POST.get('west', 0))

		for listing in listings:
			results = gmaps.geocode(listing.address)
			lat = results[0]['geometry']['location']['lat']
			lng = results[0]['geometry']['location']['lng']

			if lat <= n_bound and lat >= s_bound and lng <= e_bound and lng >= w_bound:
				d = {}
				d['address']     = listing.address
				d['lister']      = listing.lister_id
				d['startDate']   = listing.startDate.strftime("%m/%d/%y")
				d['endDate']     = listing.endDate.strftime("%m/%d/%y")
				d['rent']        = listing.rent
				d['bedrooms']    = listing.bedrooms
				d['bathrooms']   = listing.bathrooms
				d['sqft']        = listing.sqft
				d['isApartment'] = listing.isApartment
				d['website']     = listing.website
				d['comments']    = listing.comments
				d['lat'] = lat
				d['lng'] = lng
				area_listings.append(d)

		return HttpResponse(json.dumps(area_listings), content_type='application/json')


	return render(request, 'map_query.html')

def area_listing(request):
	return render(request, 'area_listing.html')

irishcribs/templates/add_listing.html
  
{% extends 'base_users.html' %}

{% block title %}Add Listing{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Add Listing</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <!--{{ form }}-->
            <button type="submit" class="btn btn-outline-green btn-block">Add New Listing</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

irishcribs/templates/add_sublet.html
{% extends 'base_users.html' %}

{% block title %}Add Sublet{% endblock %}

{% block content %}
	<div class="row justify-content-center">
		<div class="col-lg-8 col-md-10 col-sm-12">
			<div class="card">
				<div class="card-body">
					<h3 class="card-title">Add Sublet</h3>
					<form method="post" novalidate>
						{% csrf_token %}
						{% include 'includes/form.html' %}
						<!--{{ form }}-->
						<button type="submit" class="btn btn-outline-green btn-block">Add New Sublet</button>
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

irishcribs/templates/base.html
{% load static %}<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Irish Cribs{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/homeicon.ico' %}"/>
	<style>
		h1{
  			text-align: center;
  			font-size: 72px;
  			font-family: 'Verdana';
  			color: goldenrod;
  			font-weight: bold;
  			padding-bottom: 0px;
		}

		a{
	  		text-decoration: none;
  			color: goldenrod;
		}

		.userhead {
  			display: block;
  			padding: 10px;
  			text-align: center;
  			box-sizing: border-box;
  			top: 0;
  			background-color: navy;
			margin-bottom: 15px;
		}

		.userhead-title {
  			font-size: 72px;
  			font-family: 'Verdana';
  			color: goldenrod;
  			font-weight: bold;
  			padding-bottom: 0px;
		}

		.userhead-content {
  			font-size: 18px;
  			font-family: 'Open Sans';
  			color: white;
		}

		a.heading{
  			text-align: center;
		}

		a:hover{
  			text-decoration: none;
		}

		.btn-delete {
  			background-color: red;
  			border: 1px solid red;
  			border-radius: 3px;
  			color: white;
  			padding: 0.5rem;
		}

		.btn-edit {
  			background-color: green;
  			border: 1px solid green;
  			border-radius: 3px;
  			color: white;
  			padding: 0.5rem;
		}

		.btn--block {
  			/*display: block;*/
  			width: 30%;
		}
 


		.column {
      		float: left;
      		width: 25%;
      		padding: 0 10px;
	    	margin-bottom: 10px;
    	}

    	.row {margin: 0 -5px;}

    	.row:after {
      		content: "";
      		display: table;
      		clear: both;
    	}

    	@media screen and (max-width: 700px) {
      		.column {
        		width: 100%;
        		display: block;
        		margin-bottom: 20px;
      		}
    	}

		.fa-primary{
			color: green;
		}

		.fa-secondary{
			color: green;
		}

		.add-btn-block{
			display: block;
			width: 100%;
			border: none;
			text-align: center;
			background-color: green;
			color: black;
		}

    </style>

    {% block stylesheet %}{% endblock %}
  </head>
  <body>
  	<div class="userhead">
       <p class="userhead-title"><a href="{% url 'home' %}">IRISH CRIBS</a></p>
       <p class="userhead-content">Welcome to Irish Cribs!</p>
  	</div>	
    {% block body %}

	<div class="container">
        {% block content %}
        {% endblock %}

		{% block sidebar %}
		{% endblock %}
	</div>
    {% endblock body %}
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

irishcribs/templates/filter_sublet_form.html
{% extends 'base_users.html' %}

{% block title %}Filter Sublets{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Filter Sublets</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <!--{{ form }}-->
            <button type="submit" class="btn btn-outline-green btn-block">Filter</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

irishcribs/templates/homepage.html
{% load static %}
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <script defer src="{% static 'js/about.js' %}"></script>
  <link rel="stylesheet" href="{% static 'css/about.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/fa.css' %}"/>
  <!--<link rel="stylesheet" href="{% static 'css/card.css' %}"/>-->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700&display=swap" rel="stylesheet"/>
  <link href= "https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet">
  <link rel="shortcut icon" type="image/ico" href="{% static 'img/homeicon.ico' %}"/>
  <title>Home</title>
  <style>
    * {
      box-sizing: border-box;
    }

    .column {
      float: left;
      width: 25%;
      padding: 0 10px;
	    margin-bottom: 10px;
    }

    .row {margin: 0 -5px;}

    .row:after {
      content: "";
      display: table;
      clear: both;
    }

    @media screen and (max-width: 700px) {
      .column {
        width: 100%;
        display: block;
        margin-bottom: 20px;
      }
    }

    .card {
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
      padding: 16px;
      text-align: center;
      background-color: #f1f1f1;
    }

    .card-text {
      color: white;
    }

    .card-link {
      color: green;
    }

    .card-title {
      font-size: 40px;
      font-family: 'Verdana';
      color: goldenrod;
    }

    .fa-primary {
      color: green;
    }

  .fa-secondary {
    color: green;
  }

  .userhead {
  display: block;
  padding: 10px;
  text-align: center;
  box-sizing: border-box;
  top: 0;
  background-color: navy;
}

.userhead-title {
  font-size: 72px;
  font-family: 'Verdana';
  color: goldenrod;
  font-weight: bold;
  padding-bottom: 0px;
}

.userhead-content {
  font-size: 18px;
  font-family: 'Open Sans';
  color: white;
}

.userhead-content a {
  color: green;
}
  
  </style>
</head>


<body>
  <main>
    <div class="userhead">
      <p class="userhead-title">IRISH CRIBS</p>
	    <p class="userhead-content">Welcome to Irish Cribs! Take a look at off-campus housing in the South Bend area.</p>
    </div>
   </main>
  <nav class="navbar">
    <ul class="navbar-nav">
      <li class="logo">
        <a href="{% url 'home' %}" class="nav-link">
          <span class="link-text logo-text" style="font-size: medium">Irish Cribs</span>
          <svg
            aria-hidden="true"
            focusable="false"
            data-prefix="fad"
            data-icon="angle-double-right"
            role="img"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 448 512"
            class="svg-inline--fa fa-angle-double-right fa-w-14 fa-5x"
          >
            <g class="fa-group">
              <path
                fill="currentColor"
                d="M224 273L88.37 409a23.78 23.78 0 0 1-33.8 0L32 386.36a23.94 23.94 0 0 1 0-33.89l96.13-96.37L32 159.73a23.94 23.94 0 0 1 0-33.89l22.44-22.79a23.78 23.78 0 0 1 33.8 0L223.88 239a23.94 23.94 0 0 1 .1 34z"
                class="fa-secondary"
              ></path>
              <path
                fill="currentColor"
                d="M415.89 273L280.34 409a23.77 23.77 0 0 1-33.79 0L224 386.26a23.94 23.94 0 0 1 0-33.89L320.11 256l-96-96.47a23.94 23.94 0 0 1 0-33.89l22.52-22.59a23.77 23.77 0 0 1 33.79 0L416 239a24 24 0 0 1-.11 34z"
                class="fa-primary"
              ></path>
            </g>
          </svg>
        </a>
      </li>

      <li class="nav-item">
        <a href="{% url 'show_listing' %}" class="nav-link">
		      <i class="fas fa-home fa-primary fa-secondary fa-2x"></i>
          <span class="link-text">Listings</span>
        </a>
      </li>

      <li class="nav-item">
        <a href="{% url 'show_sublet' %}" class="nav-link">
		      <i class="fas fa-building fa-primary fa-secondary fa-2x"></i>
          <span class="link-text">Sublets</span>
        </a>
      </li>

      <li class="nav-item">
        <a href="{% url 'filter_listing_form' %}" class="nav-link">
          <i class="fas fa-question fa-primary fa-secondary fa-2x"></i>
		      <span class="link-text">Filter Listings</span>
        </a>
      </li>
      
	  <li class="nav-item">
        <a href="{% url 'filter_sublet_form' %}" class="nav-link">
          <i class="fas fa-city fa-primary fa-secondary fa-2x"></i>
		      <span class="link-text">Filter Sublets</span>
        </a>
      </li>
      
	  <li class="nav-item" id="themeButton">
      {% if user.is_authenticated %}
        <a href="{% url 'user_account' %}" class="nav-link">
		     <i class="fas fa-user fa-primary fa-secondary fa-2x"></i>
         <span class="link-text">Account</span>
        </a>
      {% else %}
        <a href="{% url 'login' %}" class="nav-link">
          <i class="fas fa-user fa-primary fa-secondary fa-2x"></i>
          <span class="link-text">Login</span>
        </a>
      {% endif %}  
      </li>
    </ul>
  </nav>

</body>

irishcribs/templates/show_listing.html
{% load static %}
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<script defer src="{% static 'js/about.js' %}"></script>
  	<link rel="stylesheet" href="{% static 'css/about.css' %}"/>
  	<link rel="stylesheet" href="{% static 'css/fa.css' %}"/>
  	<!--<link rel="stylesheet" href="{% static 'css/card.css' %}"/>-->
  	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700&display=swap" rel="stylesheet"/>
  	<link href= "https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet">
  	<link rel="shortcut icon" type="image/ico" href="{% static 'img/homeicon.ico' %}"/>	
    <title>Listings</title>
    <style>
		@gray-darker:               #444444;
		@gray-dark:                 #696969;
		@gray:                      #999999;
		@gray-light:                #cccccc;
		@gray-lighter:              #ececec;
		@gray-lightest:             lighten(@gray-lighter,4%);
        
		*,
		*::before,
		*::after { 
 			 box-sizing: border-box;
		}		

		html {
  			background-color: #f0f0f0;
		}

		body {
  			color: @gray;
  			font-family: 'Roboto','Helvetica Neue', Helvetica, Arial, sans-serif;
  			font-style: normal;
  			font-weight: 400;
  			letter-spacing: 0;
  			//padding: 1rem;
  			text-rendering: optimizeLegibility;
  			-webkit-font-smoothing: antialiased;
  			-moz-osx-font-smoothing: grayscale;
  			-moz-font-feature-settings: "liga" on;
		}

		img {
  			height: auto;
  			max-width: 100%;
  			vertical-align: middle;
		}

		h1{
  			text-align: center;
  			font-size: 72px;
  			font-family: 'Verdana';
  			color: goldenrod;
  			font-weight: bold;
  			padding-bottom: 0px;
		}

		a{
	  		text-decoration: none;
  			color: goldenrod;
		}

		.userhead {
  			display: block;
  			padding: 10px;
  			text-align: center;
  			box-sizing: border-box;
  			top: 0;
  			background-color: navy;
		}

		.userhead-title {
  			font-size: 72px;
  			font-family: 'Verdana';
  			color: goldenrod;
  			font-weight: bold;
  			padding-bottom: 0px;
		}

		.userhead-content {
  			font-size: 18px;
  			font-family: 'Open Sans';
  			color: white;
		}

		a.heading{
  			text-align: center;
		}

		a:hover{
  			text-decoration: none;
		}

		.btn-delete {
  			background-color: red;
  			border: 1px solid red;
  			border-radius: 3px;
  			color: white;
  			padding: 0.5rem;
		}

		.btn-edit {
  			background-color: green;
  			border: 1px solid green;
  			border-radius: 3px;
  			color: white;
  			padding: 0.5rem;
		}

		.btn--block {
  			/*display: block;*/
  			width: 30%;
		}
 
		.cards {
  			display: flex;
  			flex-wrap: wrap;
  			list-style: none;
  			margin: 0;
  			padding: 0;
		}

		.cards__item {
  			display: flex;
  			padding: 1rem;
  			@media(min-width: 40rem) {
    			width: 50%;
  			}
  			@media(min-width: 56rem) {
    			width: 33.3333%;
  			}
		}

		.card {
  			background-color: rgb(226, 222, 222);
  			border-radius: 0.25rem;
  			box-shadow: 0 20px 40px -14px rgba(0,0,0,0.25);
  			display: flex;
  			flex-direction: column;
  			overflow: hidden;
  			&:hover {
    			.card__image {
      				filter: contrast(100%);
    			}
  			}
		}

		.card__content {
  			display: flex;
  			flex: 1 1 auto;
  			flex-direction: column;
  			padding: 1rem;
		}

		.card__image {
  			background-position: center center;
  			background-repeat: no-repeat;
  			background-size: cover;
  			border-top-left-radius: 0.25rem;
  			border-top-right-radius: 0.25rem;
  			filter: contrast(70%);
  			filter: saturate(180%);
  			overflow: hidden;
  			position: relative;
  			transition: filter 0.5s cubic-bezier(.43,.41,.22,.91);;
  			&::before {
    			content: "";
	  			display: block;
    			padding-top: 56.25%; // 16:9 aspect ratio
  			}
  			@media(min-width: 40rem) {
    			&::before {
      				padding-top: 66.6%; // 3:2 aspect ratio
    			}
  			}
		}

		.card__image--shamrock {
  			background-image: url('/static/css/img/shamrock.JPG');
		}

		.card__title {
  			color: @gray-dark;
  			font-size: 1.25rem;
  			font-weight: 300;
  			letter-spacing: 2px;
  			text-transform: uppercase;
		}

		.card__text {
  			flex: 1 1 auto;
  			font-size: 0.875rem;
  			line-height: 1.5;
  			margin-bottom: 1.25rem;
		}

		.card-link {
  			color: rgb(4, 92, 19);
  			text-decoration: underline;
		}

		.column {
      		float: left;
      		width: 25%;
      		padding: 0 10px;
	    	margin-bottom: 10px;
    	}

    	.row {margin: 0 -5px;}

    	.row:after {
      		content: "";
      		display: table;
      		clear: both;
    	}

    	@media screen and (max-width: 700px) {
      		.column {
        		width: 100%;
        		display: block;
        		margin-bottom: 20px;
      		}
    	}

		.fa-primary{
			color: green;
		}

		.fa-secondary{
			color: green;
		}

		.add-btn-block{
			display: block;
			width: 100%;
			border: none;
			text-align: center;
			background-color: green;
			color: black;
		}

    </style>

<body> 
    <main>
      <div class="userhead">
        <p class="userhead-title"><a href="{% url 'home' %}">IRISH CRIBS</a></p>
        <p class="userhead-content">Welcome to Irish Cribs! Take a look at off-campus housing in the South Bend area.</p>
		{% if user.is_authenticated %}
		<p class="userhead-content">You can also click <a href="{% url 'add_listing' %}">here</a> to add a listing.</p>
		{% endif %}
      </div>
        <ul class="cards"> 
        {% for listing in listings %} 
            <li class="cards__item"> 
                <div class="card"> 
                    <div class="card__image card__image--shamrock"></div> 
                    <div class="card__content"> 
                        <div class="card__title" style="color:green">Listing</div> 
                        <ul class="card__text">
                            <li><b style="color: navy">Address: </b>{{ listing.address }}</li>

                          {% if listing.startDate %}
                            <li><b style="color: navy">Start Date: </b>{{ listing.startDate }}</li>
                          {% else %}
                            <li><b style="color: navy">Start Date: </b>N/A</li>
                          {% endif %}

                          {% if listing.endDate %}
                            <li><b style="color: navy">End Date: </b>{{ listing.endDate }}</li>
                          {% else %}
                            <li><b style="color: navy">End Date: </b>N/A</li>
                          {% endif %}

                          {% if listing.rent %}
                            <li><b style="color: navy">Rent: </b>${{ listing.rent }}/month</li>
                          {% else %}
                            <li><b style="color: navy">Rent: </b>N/A</li>
                          {% endif %}

                          {% if listing.bedrooms %}
                            <li><b style="color: navy">Bedrooms: </b>{{ listing.bedrooms }}</li>
                          {% else %}
                            <li><b style="color: navy">Bedrooms: </b>N/A</li>
                          {% endif %}

                          {% if listing.bathrooms %}
                            <li><b style="color: navy">Bathrooms: </b>{{ listing.bathrooms }}</li>
                          {% else %}
                            <li><b style="color: navy">Bathrooms: </b>N/A</li>
                          {% endif %}

                          {% if listing.sqft %}
                            <li><b style="color: navy">Square Footage: </b>{{ listing.sqft }} sq. ft.</li>
                          {% else %}
                            <li><b style="color: navy">Square Footage: </b>N/A</li>
                          {% endif %}

                          {% if listing.isApartment %}
                            {% ifequal listing.isApartment 1 %}
                              <li><b style="color: navy">Apartment: </b>Yes</li>
                            {% else %}
                              <li><b style="color: navy">Apartment: </b>No</li>
                            {% endifequal %}
                          {% else %}
                            <li><b style="color: navy">Apartment: </b>N/A</li>
                          {% endif %}

                          {% if listing.website %}
                            <li><b style="color: navy">Link: </b><a href="https://{{ listing.website }}" class="card-link">{{ listing.website }}</a></li>
                          {% else %}
                            <li><b style="color: navy">Website: </b>N/A</li>
                          {% endif %}

                          {% if listing.comments %}
                            <li><b style="color: navy">Comments: </b>{{ listing.comments }}</li>
                          {% else %}
                            <li><b style="color: navy">Comments: </b>N/A</li>
                          {% endif %}
                        </ul>
                        {% ifequal user listing.lister %}
                          <button class="btn-delete btn--block card__btn" type="submit"><a href="{% url 'delete_listing' pk=listing.address %}">Delete</a></button>
                          <button class="btn-edit btn--block card__btn" type="submit"><a href="{% url 'edit_listing' pk=listing.address %}">Edit</a></button>
                        {% endifequal %}
                    </div> 
                </div> 
            </li> 
        {% endfor %}
        </ul>
	{% if user.is_authenticated %}
	<div id="add-button-id" style="text-align: center">
    	<button class="btn-edit card__btn" type="submit" style="margin-bottom: 10px; width: 40%"><a href="{% url 'add_listing' %}">Add a New Listing</a></button>
	</div>
	{% endif %}
    </main> 
<nav class="navbar">
    <ul class="navbar-nav">
      <li class="logo">
        <a href="{% url 'home' %}" class="nav-link">
          <span class="link-text logo-text" style="font-size: medium">Irish Cribs</span>
          <svg
            aria-hidden="true"
            focusable="false"
            data-prefix="fad"
            data-icon="angle-double-right"
            role="img"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 448 512"
            class="svg-inline--fa fa-angle-double-right fa-w-14 fa-5x"
          >
            <g class="fa-group">
              <path
                fill="currentColor"
                d="M224 273L88.37 409a23.78 23.78 0 0 1-33.8 0L32 386.36a23.94 23.94 0 0 1 0-33.89l96.13-96.37L32 159.73a23.94 23.94 0 0 1 0-33.89l22.44-22.79a23.78 23.78 0 0 1 33.8 0L223.88 239a23.94 23.94 0 0 1 .1 34z"
                class="fa-secondary"
              ></path>
              <path
                fill="currentColor"
                d="M415.89 273L280.34 409a23.77 23.77 0 0 1-33.79 0L224 386.26a23.94 23.94 0 0 1 0-33.89L320.11 256l-96-96.47a23.94 23.94 0 0 1 0-33.89l22.52-22.59a23.77 23.77 0 0 1 33.79 0L416 239a24 24 0 0 1-.11 34z"
                class="fa-primary"
              ></path>
            </g>
          </svg>
        </a>
      </li>

      <li class="nav-item">
        <a href="{% url 'show_listing' %}" class="nav-link">
		      <i class="fas fa-home fa-primary fa-secondary fa-2x"></i>
          <span class="link-text">Listings</span>
        </a>
      </li>

      <li class="nav-item">
        <a href="{% url 'show_sublet' %}" class="nav-link">
		      <i class="fas fa-building fa-primary fa-secondary fa-2x"></i>
          <span class="link-text">Sublets</span>
        </a>
      </li>

      <li class="nav-item">
        <a href="{% url 'filter_listing_form' %}" class="nav-link">
          <i class="fas fa-question fa-primary fa-secondary fa-2x"></i>
		      <span class="link-text">Filter Listings</span>
        </a>
      </li>
      
	  <li class="nav-item">
        <a href="{% url 'filter_sublet_form' %}" class="nav-link">
		      <i class="fas fa-city fa-primary fa-secondary fa-2x"></i>
          <span class="link-text">Filter Sublets</span>
        </a>
      </li>

      <li class="nav-item">
        <a href="{% url 'django_messages:messages_redirect' %}" class="nav-link">
          <i class="fas fa-envelope fa-primary fa-secondary fa-2x"></i>
		      <span class="link-text">Messages</span>
        </a>
      </li>

      <li class="nav-item">
        <a href="{% url 'map_query' %}" class="nav-link">
          <i class="fas fa-search fa-primary fa-secondary fa-2x"></i>
		      <span class="link-text">Search Map</span>
        </a>
      </li>
      
	  <li class="nav-item" id="themeButton">
      {% if user.is_authenticated %}
        <a href="{% url 'user_account' %}" class="nav-link">
		     <i class="fas fa-user fa-primary fa-secondary fa-2x"></i>
         <span class="link-text">Account</span>
        </a>
      {% else %}
        <a href="{% url 'login' %}" class="nav-link">
          <i class="fas fa-user fa-primary fa-secondary fa-2x"></i>
          <span class="link-text">Login</span>
        </a>
      {% endif %}  
      </li>
    </ul>
  </nav>

</body>

</html>