irishcribs/django_messages/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from django_messages.views import *

app_name = 'django_messages'
urlpatterns = [
    url(r'^$', RedirectView.as_view(permanent=True, url='inbox/'), name='messages_redirect'),
    url(r'^inbox/$', inbox, name='messages_inbox'),
    url(r'^outbox/$', outbox, name='messages_outbox'),
    url(r'^compose/$', compose, name='messages_compose'),
    url(r'^compose/(?P<recipient>[\w.@+-]+)/$', compose, name='messages_compose_to'),
    url(r'^reply/(?P<message_id>[\d]+)/$', reply, name='messages_reply'),
    url(r'^view/(?P<message_id>[\d]+)/$', view, name='messages_detail'),
    url(r'^delete/(?P<message_id>[\d]+)/$', delete, name='messages_delete'),
    url(r'^undelete/(?P<message_id>[\d]+)/$', undelete, name='messages_undelete'),
    url(r'^trash/$', trash, name='messages_trash'),
]

irishcribs/irishcribs/urls.py
from django.contrib import admin
from django.urls import path, re_path, register_converter
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from . import converts

from home import views as home_view
from Users import views as user_views
from Listings import views as listing_views
from Listings.views import EditListingView, DeleteListingView

from Sublets import views as sublet_views
from Sublets.views import EditSubletView, DeleteSubletView

from MapQuery import views as map_views

register_converter(converts.FloatUrlParameterConverter, 'float')

urlpatterns = [
	path('accounts/', include('django.contrib.auth.urls')),
	path('accounts/signup/', user_views.signup, name='signup'),
    path('accounts/login/', user_views.login, name='login'),
    path('userAccount/', user_views.accountPage, name='user_account'),

	path('listings/', listing_views.view_listings, name='show_listing'),
    path('addlisting/', listing_views.add_listings, name='add_listing'),
    path('editlisting/<pk>/', EditListingView.as_view(), name='edit_listing'),
    path('deletelisting/<pk>/', DeleteListingView.as_view(), name='delete_listing'),
    #path('deleteListing/', listing_views.delete_listing, name='delete_listing'),
    path('filterListings/', listing_views.filter_listing_form, name='filter_listing_form'),
    #path('filteredListings/<float:bedrooms>/<float:bathrooms>/<float:rent>/<float:sqft>/<float:isApartment>/', listing_views.show_filtered_listings, name='filtered'),
    path('filteredListings/', listing_views.filtered_listings, name='filtered_listings'),
	path('messages/', include('django_messages.urls', namespace='django_messages')),
	path('sublets/', sublet_views.view_sublets, name='show_sublet'),
    path('addsublet/', sublet_views.add_sublets, name='add_sublet'),
    path('editsublet/<pk>/', EditSubletView.as_view(), name='edit_sublet'),
    path('deletesublet/<pk>/', DeleteSubletView.as_view(), name='delete_sublet'),
    path('filtersublets/', sublet_views.filter_sublet_form, name='filter_sublet_form'),
    path('filteredsublets/', sublet_views.filtered_sublets, name='filtered_sublets'),
    path('admin/', admin.site.urls),
    path('mapquery/', map_views.map_query, name='map_query'),
	path('area_listing/', map_views.area_listing, name='area_listing'),

	path('', home_view.home, name='home'),
	path('home/', home_view.home, name='home')
]

irishcribs/django_messages/forms.py
from django import forms
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone

if "pinax.notifications" in settings.INSTALLED_APPS and getattr(settings, 'DJANGO_MESSAGES_NOTIFY', True):
    from pinax.notifications import models as notification
else:
    notification = None

from django_messages.models import Message
from django_messages.fields import CommaSeparatedUserField

class ComposeForm(forms.Form):
    """
    A simple default form for private messages.
    """
    recipient = CommaSeparatedUserField(label=_(u"Recipient"))
    subject = forms.CharField(label=_(u"Subject"), max_length=140)
    body = forms.CharField(label=_(u"Body"),
        widget=forms.Textarea(attrs={'rows': '12', 'cols':'55'}))


    def __init__(self, *args, **kwargs):
        recipient_filter = kwargs.pop('recipient_filter', None)
        super(ComposeForm, self).__init__(*args, **kwargs)
        if recipient_filter is not None:
            self.fields['recipient']._recipient_filter = recipient_filter


    def save(self, sender, parent_msg=None):
        recipients = self.cleaned_data['recipient']
        subject = self.cleaned_data['subject']
        body = self.cleaned_data['body']
        message_list = []
        for r in recipients:
            msg = Message(
                sender = sender,
                recipient = r,
                subject = subject,
                body = body,
            )
            if parent_msg is not None:
                msg.parent_msg = parent_msg
                parent_msg.replied_at = timezone.now()
                parent_msg.save()
            msg.save()
            message_list.append(msg)
            if notification:
                if parent_msg is not None:
                    notification.send([sender], "messages_replied", {'message': msg,})
                    notification.send([r], "messages_reply_received", {'message': msg,})
                else:
                    notification.send([sender], "messages_sent", {'message': msg,})
                    notification.send([r], "messages_received", {'message': msg,})
        return message_list

irishcribs/django_messages/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.template import RequestContext
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.translation import ugettext as _
from django.utils import timezone
try:
    from django.core.urlresolvers import reverse
except ImportError:
    from django.urls import reverse
from django.conf import settings

from django_messages.models import Message
from django_messages.forms import ComposeForm
from django_messages.utils import format_quote, get_user_model, get_username_field

User = get_user_model()

if "pinax.notifications" in settings.INSTALLED_APPS and getattr(settings, 'DJANGO_MESSAGES_NOTIFY', True):
    from pinax.notifications import models as notification
else:
    notification = None

@login_required
def inbox(request, template_name='django_messages/inbox.html'):
    """
    Displays a list of received messages for the current user.
    Optional Arguments:
        ``template_name``: name of the template to use.
    """
    message_list = Message.objects.inbox_for(request.user)
    return render(request, template_name, {
        'message_list': message_list,
    })

@login_required
def outbox(request, template_name='django_messages/outbox.html'):
    """
    Displays a list of sent messages by the current user.
    Optional arguments:
        ``template_name``: name of the template to use.
    """
    message_list = Message.objects.outbox_for(request.user)
    return render(request, template_name, {
        'message_list': message_list,
    })

@login_required
def trash(request, template_name='django_messages/trash.html'):
    """
    Displays a list of deleted messages.
    Optional arguments:
        ``template_name``: name of the template to use
    Hint: A Cron-Job could periodicly clean up old messages, which are deleted
    by sender and recipient.
    """
    message_list = Message.objects.trash_for(request.user)
    return render(request, template_name, {
        'message_list': message_list,
    })

@login_required
def compose(request, recipient=None, form_class=ComposeForm,
        template_name='django_messages/compose.html', success_url=None, recipient_filter=None):
    """
    Displays and handles the ``form_class`` form to compose new messages.
    Required Arguments: None
    Optional Arguments:
        ``recipient``: username of a `django.contrib.auth` User, who should
                       receive the message, optionally multiple usernames
                       could be separated by a '+'
        ``form_class``: the form-class to use
        ``template_name``: the template to use
        ``success_url``: where to redirect after successfull submission
    """
    if request.method == "POST":
        sender = request.user
        form = form_class(request.POST, recipient_filter=recipient_filter)
        if form.is_valid():
            form.save(sender=request.user)
            messages.info(request, _(u"Message successfully sent."))
            if success_url is None:
                success_url = reverse('django_messages:messages_inbox')
            if 'next' in request.GET:
                success_url = request.GET['next']
            return HttpResponseRedirect(success_url)
    else:
        form = form_class()
        if recipient is not None:
            recipients = [u for u in User.objects.filter(**{'%s__in' % get_username_field(): [r.strip() for r in recipient.split('+')]})]
            form.fields['recipient'].initial = recipients
    return render(request, template_name, {
        'form': form,
    })

@login_required
def reply(request, message_id, form_class=ComposeForm,
        template_name='django_messages/compose.html', success_url=None,
        recipient_filter=None, quote_helper=format_quote,
        subject_template=_(u"Re: %(subject)s"),):
    """
    Prepares the ``form_class`` form for writing a reply to a given message
    (specified via ``message_id``). Uses the ``format_quote`` helper from
    ``messages.utils`` to pre-format the quote. To change the quote format
    assign a different ``quote_helper`` kwarg in your url-conf.

    """
    parent = get_object_or_404(Message, id=message_id)

    if parent.sender != request.user and parent.recipient != request.user:
        raise Http404

    if request.method == "POST":
        sender = request.user
        form = form_class(request.POST, recipient_filter=recipient_filter)
        if form.is_valid():
            form.save(sender=request.user, parent_msg=parent)
            messages.info(request, _(u"Message successfully sent."))
            if success_url is None:
                success_url = reverse('django_messages:messages_inbox')
            return HttpResponseRedirect(success_url)
    else:
        form = form_class(initial={
            'body': quote_helper(parent.sender, parent.body),
            'subject': subject_template % {'subject': parent.subject},
            'recipient': [parent.sender,]
            })
    return render(request, template_name, {
        'form': form,
    })

@login_required
def delete(request, message_id, success_url=None):
    """
    Marks a message as deleted by sender or recipient. The message is not
    really removed from the database, because two users must delete a message
    before it's save to remove it completely.
    A cron-job should prune the database and remove old messages which are
    deleted by both users.
    As a side effect, this makes it easy to implement a trash with undelete.

    You can pass ?next=/foo/bar/ via the url to redirect the user to a different
    page (e.g. `/foo/bar/`) than ``success_url`` after deletion of the message.
    """
    user = request.user
    now = timezone.now()
    message = get_object_or_404(Message, id=message_id)
    deleted = False
    if success_url is None:
        success_url = reverse('django_messages:messages_inbox')
    if 'next' in request.GET:
        success_url = request.GET['next']
    if message.sender == user:
        message.sender_deleted_at = now
        deleted = True
    if message.recipient == user:
        message.recipient_deleted_at = now
        deleted = True
    if deleted:
        message.save()
        messages.info(request, _(u"Message successfully deleted."))
        if notification:
            notification.send([user], "messages_deleted", {'message': message,})
        return HttpResponseRedirect(success_url)
    raise Http404

@login_required
def undelete(request, message_id, success_url=None):
    """
    Recovers a message from trash. This is achieved by removing the
    ``(sender|recipient)_deleted_at`` from the model.
    """
    user = request.user
    message = get_object_or_404(Message, id=message_id)
    undeleted = False
    if success_url is None:
        success_url = reverse('django_messages:messages_inbox')
    if 'next' in request.GET:
        success_url = request.GET['next']
    if message.sender == user:
        message.sender_deleted_at = None
        undeleted = True
    if message.recipient == user:
        message.recipient_deleted_at = None
        undeleted = True
    if undeleted:
        message.save()
        messages.info(request, _(u"Message successfully recovered."))
        if notification:
            notification.send([user], "messages_recovered", {'message': message,})
        return HttpResponseRedirect(success_url)
    raise Http404

@login_required
def view(request, message_id, form_class=ComposeForm, quote_helper=format_quote,
        subject_template=_(u"Re: %(subject)s"),
        template_name='django_messages/view.html'):
    """
    Shows a single message.``message_id`` argument is required.
    The user is only allowed to see the message, if he is either
    the sender or the recipient. If the user is not allowed a 404
    is raised.
    If the user is the recipient and the message is unread
    ``read_at`` is set to the current datetime.
    If the user is the recipient a reply form will be added to the
    tenplate context, otherwise 'reply_form' will be None.
    """
    user = request.user
    now = timezone.now()
    message = get_object_or_404(Message, id=message_id)
    if (message.sender != user) and (message.recipient != user):
        raise Http404
    if message.read_at is None and message.recipient == user:
        message.read_at = now
        message.save()

    context = {'message': message, 'reply_form': None}
    if message.recipient == user:
        form = form_class(initial={
            'body': quote_helper(message.sender, message.body),
            'subject': subject_template % {'subject': message.subject},
            'recipient': [message.sender,]
            })
        context['reply_form'] = form
    return render(request, template_name, context)

irishcribs/django_messages/templates/django_messages/base.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
{% endblock %}
{% block sidebar %}
<ul class="subnavilist list-group">
    <li class="list-group-item"><a href="{% url 'django_messages:messages_inbox' %}">&raquo;&nbsp;{% trans "Inbox" %}</a></li>
    <li class="list-group-item"><a href="{% url 'django_messages:messages_outbox' %}">&raquo;&nbsp;{% trans "Sent Messages" %}</a></li>
    <li class="list-group-item"><a href="{% url 'django_messages:messages_compose' %}">&raquo;&nbsp;{% trans "New Message" %}</a></li>
    <li class="list-group-item"><a href="{% url 'django_messages:messages_trash' %}">&raquo;&nbsp;{% trans "Trash" %}</a></li>
</ul>
{% endblock %}

irishcribs/django_messages/templates/django_messages/compose.html
{% extends "django_messages/base.html" %}
{% load i18n %}

{% block content %}
  <h2 style="text-align: center;">{% trans "Compose Message"%}</h2>
  <form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" style="border-radius: 3px; background-color: green; border: none; margin: 2rem; color: white;" value="{% trans "Send" %} &raquo;"/>
  </form>
{% endblock %}

irishcribs/django_messages/templates/django_messages/inbox.html
{% extends "django_messages/base.html" %}
{% load i18n %}

{% block content %}
<h2 style="text-align: center;">{% trans "Inbox" %}</h2>
{% if message_list %}
<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
			<th scope="col">{% trans "Sender" %}</th>
			<th scope="col">{% trans "Subject" %}</th>
			<th scope="col">{% trans "Received" %}</th>
			<th scope="col">{% trans "Action" %}</th>
		</tr>
    </thead>
    <tbody>
{% for message in message_list %}
    <tr>
        <td>{{ message.sender }}</td>
        <td>
            {% if message.new %}<strong>{% endif %}
            {% if message.replied %}<em>{% endif %}
            <a href="{{ message.get_absolute_url }}">{{ message.subject }}</a>
            {% if message.replied %}</em>{% endif %}
            {% if message.new %}</strong>{% endif %}</td>
        <td>{{ message.sent_at|date:_("DATETIME_FORMAT") }}</td>
        <td><a href="{% url 'django_messages:messages_delete' message.id %}">{% trans "delete" %}</a></td>
    </tr>
{% endfor %}
    </tbody>
</table>
{% else %}
<p>{% trans "No messages." %}</p>
{% endif %}
{% endblock %}

irishcribs/django_messages/templates/django_messages/new_message.html
{% load i18n %}

{% blocktrans with recipient=message.recipient sender=message.sender %}Hello {{ recipient }},

you received a private message from {{ sender }} with
the following contents:{% endblocktrans %}

{{ message.body|safe }}

--
{% blocktrans %}Sent from {{ site_url }}{% endblocktrans %}
{% trans "Inbox" %}: {{ site_url }}{% url 'django_messages:messages_inbox' %}
{% trans "Reply" %}: {{ site_url }}{% url 'django_messages:messages_reply' message.pk %}

irishcribs/django_messages/templates/django_messages/outbox.html
{% extends "django_messages/base.html" %}
{% load i18n %}

{% block content %}
<h2 style="text-align: center;">{% trans "Sent Messages" %}</h1>
{% if message_list %}
<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
		  <th scope="col">{% trans "Recipient" %}</th>
		  <th scope="col">{% trans "Subject" %}</th>
		  <th scope="col">{% trans "Sent" %}</th>
		  <th scope="col">{% trans "Action" %}</th>
		</tr>
    </thead>
    <tbody>
{% for message in message_list %}
    <tr>
        <td>{{ message.recipient }}</td>
        <td>
        <a href="{{ message.get_absolute_url }}">{{ message.subject }}</a>
        </td>
        <td>{{ message.sent_at|date:_("DATETIME_FORMAT") }}</td>
        <td><a href="{% url 'django_messages:messages_delete' message.id %}?next={% url 'django_messages:messages_outbox' %}">{% trans "delete" %}</a></td>
    </tr>
{% endfor %}
    </tbody>
</table>
{% else %}
<p>{% trans "No messages." %}</p>
{% endif %}
{% endblock %}

irishcribs/django_messages/templates/django_messages/trash.html
{% extends "django_messages/base.html" %}
{% load i18n %}

{% block content %}
<h2 style="text-align: center;">{% trans "Deleted Messages" %}</h1>
{% if message_list %}
<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
		  <th scope="col">{% trans "Sender" %}</th>
		  <th scope="col">{% trans "Subject" %}</th>
		  <th scope="col">{% trans "Date" %}</th>
		  <th scope="col">{% trans "Action" %}</th>
		</tr>
    </thead>
    <tbody>
{% for message in message_list %}
    <tr>
        <td>{{ message.sender }}</td>
        <td>
        {{ message.subject }}
        </td>
        <td>{{ message.sent_at|date:_("DATETIME_FORMAT") }}</td>
        <td><a href="{% url 'django_messages:messages_undelete' message.id %}">{% trans "undelete" %}</a></td>
    </tr>
{% endfor %}
    </tbody>
</table>
{% else %}
<p>{% trans "No messages." %}</p>
{% endif %}
<br />
{% endblock %}

irishcribs/django_messages/templates/django_messages/view.html
{% extends "django_messages/base.html" %}
{% load i18n %}

{% block content %}
<h2 style="text-align: center;">{% trans "View Message" %}</h1>
<dl class="message-headers">
    <dt>{% trans "Subject" %}</dt>
    <dd><strong>{{ message.subject }}</strong></dd>
    <dt>{% trans "Sender" %}</dt>
    <dd>{{ message.sender }}</dd>
    <dt>{% trans "Date" %} </dt>
    <dd>{{ message.sent_at|date:_("DATETIME_FORMAT")}}</dd>
    <dt>{% trans "Recipient" %}</dt>
    <dd>{{ message.recipient }}</dd>
</dl>
{{ message.body|linebreaksbr }}<br /><br />

{% ifequal message.recipient.pk user.pk %}
<button type="button" class="btn btn-success"><a href="{% url 'django_messages:messages_reply' message.id %}">{% trans "Reply" %}</a></button>
{% endifequal %}
<button type="button" class="btn btn-danger"><a href="{% url 'django_messages:messages_delete' message.id %}">{% trans "Delete" %}</a></button>

{% comment %}Example reply_form integration
{% if reply_form %}
<h1>{% trans "Compose reply"%}</h1>
<form action="{% url 'messages_reply' message.id %}" method="post">
{% csrf_token %}
<table>
{{ reply_form.as_table }}
</table>
<input type="submit" value="{% trans "Send" %} &raquo;"/>
</form>
{% endif %}
{% endcomment %}
{% endblock %}